<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-28T17:46:44 IST" name="Suite" finished-at="2021-04-28T17:48:10 IST" duration-ms="86752">
    <groups>
    </groups>
    <test started-at="2021-04-28T17:46:44 IST" name="Test" finished-at="2021-04-28T17:48:10 IST" duration-ms="86752">
      <class name="com.Banking.TestCases.TC2_Add_Customer">
        <test-method is-config="true" signature="BrowserOpening()[pri:0, instance:com.Banking.TestCases.TC2_Add_Customer@3e3047e6]" started-at="2021-04-28T17:47:40 IST" name="BrowserOpening" finished-at="2021-04-28T17:47:46 IST" duration-ms="6417" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserOpening -->
        <test-method is-config="true" signature="method(java.lang.reflect.Method)[pri:0, instance:com.Banking.TestCases.TC2_Add_Customer@3e3047e6]" started-at="2021-04-28T17:47:46 IST" name="method" finished-at="2021-04-28T17:47:46 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Banking.TestCases.TC2_Add_Customer.AddCustomer() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method signature="AddCustomer()[pri:0, instance:com.Banking.TestCases.TC2_Add_Customer@3e3047e6]" started-at="2021-04-28T17:47:46 IST" name="AddCustomer" finished-at="2021-04-28T17:48:08 IST" duration-ms="21644" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.Banking.TestCases.TC2_Add_Customer.AddCustomer(TC2_Add_Customer.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddCustomer -->
        <test-method is-config="true" signature="BrowserClosing()[pri:0, instance:com.Banking.TestCases.TC2_Add_Customer@3e3047e6]" started-at="2021-04-28T17:48:08 IST" name="BrowserClosing" finished-at="2021-04-28T17:48:10 IST" duration-ms="2280" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserClosing -->
      </class> <!-- com.Banking.TestCases.TC2_Add_Customer -->
      <class name="com.Banking.TestCases.TestCase_Login_Verification">
        <test-method is-config="true" signature="Report()[pri:0, instance:com.Banking.TestCases.TestCase_Login_Verification@13acb0d1]" started-at="2021-04-28T17:46:44 IST" name="Report" finished-at="2021-04-28T17:46:44 IST" duration-ms="560" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Report -->
        <test-method is-config="true" signature="BrowserOpening()[pri:0, instance:com.Banking.TestCases.TestCase_Login_Verification@13acb0d1]" started-at="2021-04-28T17:46:44 IST" name="BrowserOpening" finished-at="2021-04-28T17:47:11 IST" duration-ms="27151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserOpening -->
        <test-method is-config="true" signature="method(java.lang.reflect.Method)[pri:0, instance:com.Banking.TestCases.TestCase_Login_Verification@13acb0d1]" started-at="2021-04-28T17:47:11 IST" name="method" finished-at="2021-04-28T17:47:11 IST" duration-ms="22" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.Banking.TestCases.TestCase_Login_Verification.login() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- method -->
        <test-method signature="login()[pri:0, instance:com.Banking.TestCases.TestCase_Login_Verification@13acb0d1]" started-at="2021-04-28T17:47:11 IST" name="login" finished-at="2021-04-28T17:47:31 IST" duration-ms="19811" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="BrowserClosing()[pri:0, instance:com.Banking.TestCases.TestCase_Login_Verification@13acb0d1]" started-at="2021-04-28T17:47:31 IST" name="BrowserClosing" finished-at="2021-04-28T17:47:40 IST" duration-ms="8727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserClosing -->
      </class> <!-- com.Banking.TestCases.TestCase_Login_Verification -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
